name: Lint

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check formatting
        run: |
          cargo fmt --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run clippy
        run: |
          cargo clippy --all-targets --all-features
